# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  Config
        run:   echo {DXSDK_DIR}={$HOME/cache}  >> $GITHUB_ENV
        shell: bash
        
      - name: Cache
        id:   cache
        uses: actions/cache@v1
        with:
          path: ~/cache
          key:  cache

      - name:  Cache create
        if:    steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
          7z x _DX2010_.exe DXSDK/Include -o_DX2010_
          7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
          mv _DX2010_/DXSDK $HOME/cache
          rm -fR _DX*_ _DX*_.exe
        shell: bash

      - name: search cache
        run: $DXSDK_DIR

